server:
  port: 8081

spring:
  hateoas:
    use-hal-as-default-json-media-type: false
  webflux:
    hiddenmethod:
      filter:
        enabled: true
  rsocket:
    server:
      port: 7000
      transport: tcp
  main:
    allow-cricular-references: true

management:
#  endpoint:
#    health:
#      show-details: always
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info

info:
  project:
    version: @project.version@
  java:
    version: @java.version@
  spring:
    framework:
      version: @spring-framework.version@
    data:
      version: @spring-data-bom.version@

#logging:
#  level:
#    web: DEBUG
