server:
  port: 8081

spring:
  hateoas:
    use-hal-as-default-json-media-type: false
  webflux:
    hiddenmethod:
      filter:
        enabled: true
  main:
    allow-cricular-references: true

#logging:
#  level:
#    web: DEBUG
